# 开发环境配置文件
server:
  port: 8101

spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: your_db_username
    password: your_db_password

  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    # password: your_redis_password

mybatis-plus:
  configuration:
    # 开发环境启用日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 接口文档配置
knife4j:
  basic:
    enable: true
    # 开发环境可以设置为基本认证的用户名和密码
    username: your_knife4j_username
    password: your_knife4j_password
