# 线上配置文件
server:
  port: 8101

spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: your_db_username
    password: your_db_password

  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    # password: your_redis_password

mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: org.apache.ibatis.logging.nolog.NoLogImpl

# 接口文档配置
knife4j:
  basic:
    enable: false
    # 在生产环境中不推荐使用基本认证配置
    username: your_knife4j_username
    password: your_knife4j_password
